name: FlutterCloudMusic
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  flutter_swiper: ^1.1.6
  flutter:
    sdk: flutter
  flutter_redux: ^0.7.0
  cupertino_icons: ^1.0.0
  connectivity: ^2.0.2
  intl: ^0.16.1
  audioplayers: ^0.17.4
  provider: ^4.3.3
  sqflite: ^1.3.2+3
  flutter_screenutil: ^4.0.3+1
  cached_network_image: ^2.5.0
  common_utils: ^1.2.4
  device_info: ^1.0.0
  flutter_keyboard_visibility: ^4.0.6
  shared_preferences: ^0.5.12
  redux: ^4.0.0
  multi_image_picker: ^4.7.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - images/tabbar/
    - images/